apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - jitesoft.tech
  - ''
  - coordination.k8s.io
  resources:
  - mariadbs
  - persistentvolumeclaims
  - leases
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - jitesoft.tech
  resources:
  - mariadbs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - persistentvolumeclaims/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
