apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mariadbs.jitesoft.tech
spec:
  group: jitesoft.tech
  names:
    kind: MariaDB
    listKind: MariadbList
    plural: mariadbs
    singular: mariadb
    categories:
      - jitesoft
      - databases
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: { }
    schema:
      openAPIV3Schema:
        type: object
        description: Mariadb is the Schema for the mariadbs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MariadbSpec defines the desired state of Mariadb
            properties:
              dbName:
                description: Name of the initial database to create.
                type: string
              dbPasswordSecretKey:
                description: Secret reference key to get user password from. Defaults
                  to 'password'.
                type: string
              dbPasswordSecretName:
                description: Secret reference to get user password from.
                type: string
              dbUser:
                description: Username of initial user.
                type: string
              image:
                description: Image to use. Defaults to mariadb:10.7
                type: string
              port:
                description: Port the database should listen to, defaults to 3306.
                type: integer
              resources:
                description: Resource specification for the mariadb instance.
                properties:
                  limits:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    description: 'Limits describes the maximum amount of compute resources
                      allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                    type: object
                  requests:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    description: 'Requests describes the minimum amount of compute
                      resources required. If Requests is omitted for a container,
                      it defaults to Limits if that is explicitly specified, otherwise
                      to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                    type: object
                type: object
            required:
            - dbName
            - dbUser
            - dbPasswordSecretName
            type: object
          status:
            type: object
            properties:
              currentState:
                type: integer
