apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadbs-controller-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: mariadbs-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - watch
      - list
      - get
  - apiGroups:
      - apps/v1
    resources:
      - deployments
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - jitesoft.tech
    resources:
      - mariadbs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - jitesoft.tech
    resources:
      - mariadbs/finalizers
    verbs:
      - update
  - apiGroups:
      - jitesoft.tech
    resources:
      - mariadbs/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mariadbs-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mariadbs-manager-role
subjects:
  - kind: ServiceAccount
    name: mariadbs-controller-manager
    namespace: core
